-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.User exposing (email, id, name, posts)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
id : SelectionSet Api.Scalar.Id Api.Object.User
id =
    Object.selectionForField "id" [] (Object.scalarDecoder |> Decode.map Api.Scalar.Id)


{-| -}
email : SelectionSet (Maybe String) Api.Object.User
email =
    Object.selectionForField "email" [] (Decode.string |> Decode.nullable)


{-| -}
name : SelectionSet String Api.Object.User
name =
    Object.selectionForField "name" [] Decode.string


{-| -}
posts : SelectionSet decodesTo Api.Object.Post -> SelectionSet (List decodesTo) Api.Object.User
posts object_ =
    Object.selectionForCompositeField "posts" [] object_ (identity >> Decode.list)
